spring:
  liquibase:
    change-log: classpath*:/migration/master.yml
    user: postgres
    url: jdbc:postgresql://localhost:5432/textme
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/textme
    username: postgres
    password: postgres
  jpa:
    show-sql: true